version: "3.0"

services:
  nginx:
    image: viniciusmattosrj/nginx
    restart: always
    volumes:
     - ../docker/laravel_conf:/etc/nginx/conf.d
     - ./:/var/www/html
     -  /usr/bin/ssh:/usr/bin/ssh
    links:
      - php:php
    networks:
      projetos_micro_servicos:
        ipv4_address: 10.11.0.11
    container_name: nginx
    
  php:
    image: viniciusmattosrj/php:7.3
    restart: always
    command: bash -c "sed -i \"s/post_max_size = 8M/post_max_size = 30M/\" /usr/local/etc/php/php.ini-development
                    && sed -i \"s/upload_max_filesize = 2M/upload_max_filesize = 30M/\" /usr/local/etc/php/php.ini-development
                    && sed -i \"s/xdebug.remote_enable=Off/xdebug.remote_enable=On/\" /usr/local/etc/php/php.ini-development
                    && sed -i \"s/xdebug.remote_connect_back=Off/xdebug.remote_connect_back=On/\" /usr/local/etc/php/php.ini-development
                    && sed -i \"s/xdebug.remote_port=9001/xdebug.remote_port=9000/\" /usr/local/etc/php/php.ini-development
                    && sed -i \"s/xdebug.idekey=docker/xdebug.idekey=/\" /usr/local/etc/php/php.ini-development
                    && php-fpm"
    environment:
     - XDEBUG_CONFIG=remote_host=172.17.0.1
     - PHP_IDE_CONFIG=serverName=Local
     - PHP_XDEBUG_ENABLED=1 # Set 1 to enable. 
    volumes:
     - ./:/var/www/html
     -  /usr/bin/ssh:/usr/bin/ssh
    networks:
      projetos_micro_servicos:
        ipv4_address: 10.11.0.12
    container_name: php

networks:
  projetos_micro_servicos:
   external: true
